### PR TITLE
Documentation of new INTEGRITY_CHECK error type

### PR DESCRIPTION
**Pull request by TueCN**
The optional SOAP header is not implemented and the default strategy is to always use the new INTEGRITY_CHECK error type.

### CODE REVIEW

**Comment by DaveSS** [comment]
We appreciate that the documentation being updated but are surprised that this change is not backward compatible. The latest comments on Issue 33 indicated that the INTERGRITY_CHECK option would be supported by an optional SOAP header in order to preserve backward compatibility. Why was this decision changed (or did I misunderstand the Issue 33 resolution?) 

The choice to make the INTEGRITY_CHECK error part of the default behavior will require new development on our side to support, especially since the response format for INTEGRITY_CHECK errors differs from the format used by the three previously documented error responses.  

Is this github pull request asking for comments on the documentation, or the actual change for Issue 33? We would prefer that the change to support INTEGRITY_CHECK errors was made in a way that preserves backward compatibility.

**Comment by TueCN** [comment]
Hi @DaveSS 

It is correct that integrity errors (as they are described on #33) should be reported as BUSINESS_RULE errors unless a new (optional) SOAP header is present and set to true. 
However, the SOAP header or the reporting in BUSINESS_RULE format has not been implemented/documented yet. 
If there is an actual need for having integrity errors reported as BUSINESS_RULE errors, then we will prioritize the work of this remaining implementation. 

However be aware that integrity errors reported as BUSINESS_RULE errors changes the semantics of the `location` attribute, as integrity errors do not have a `<business rule unique identifier>` segment on the format e.g. `sds:lpr:3.0.0|||01.01`. This means that there will be some breaking changes regardless. I do not see a way to avoid this.

Either the `<integrity code>` value can be inserted in the segment instead, or the segment needs to be optional, and will be omitted in case of integrity errors. 
To me, this would be more bothersome than having integrity errors reported in their own INTEGRITY_CHECK error type. Are you sure you want integrity errors on the BUSINESS_RULE format as the default behavior?

-------

Regardless, I appreciate your feedback. I do not believe the format of the new INTEGRITY_CHECK error type has been specified up front, so we have some wiggle room for changing it still, to better support end user needs.
Would it suit you better if INTEGRITY_CHECK had a format more similar to BUSINESS_RULE? 

I assume you have already read the changes in this pull request.
My suggestion is swapping `<integrity code>` and `<validation text>` so the `codeContext` of INTEGRITY_CHECK errors becomes:
`<validation type>|||<validation text>|||<integrity code>|||<param1>|||<param2>`

That way the 2 first segments are identical to BUSINESS_RULE and you can use or ignore the remaining segments as you please.

**Comment by DaveSS** [comment]
Thanks for the additional details about the INTEGRITY_CHECK error type. I do think making it more similar to BUSINESS_RULE will help with the implementation. We will need to investigate the details of supporting the 2 different options on our end before I can say whether reporting the errors as BUSINESS_RULEs unless a SOAP header is present is needed or whether we can support the INTEGRITY_CHECK format as the default.

**Comment by TueCN** [comment]
We have come to the conclusion that implementing+documenting the remaining work of #33 should be high priority regardless, as we are committed to the behavior described on #33 and the change of default behavior to match the description on #33 will be a breaking change for everybody, compared to the current behavior. 

Also, we will update the `codeContext` of INTEGRITY_CHECK errors to be on the format `<validation type>|||<validation text>|||<integrity code>|||<param1>|||<param2>` as discussed.

**Comment by MartinHylleberg** [comment]
We are uncertain if this change will lead to a change to the behaviour in regard to the header or not.
As far as I can read it seems that the optional header will not be introduced, in the sense that it is not mentioned in the file change. 

We would like a resolution to this as soon as possible since the introduction of a header will require additional implementation on our part, where as if the INTEGRITY_CHECK behaves in a similar manner to XSD, SCHEMATRON and BUSINESS_RULES validations we do not need to make changes. 

The above of course also means that we definetely agree on making the format as similar to BUSINESS_RULE as possible.

**Comment by jbraschler** [comment]
Currently, the INTEGRITY_CHECK error documentation doesn't contain a definition of the parameters that are included in the error text for the specific error types. The parameter definitions look like they can be safely inferred for the most part, but it'd be good if the documentation included a definition of the parameter values used for each error type.

**Comment by TueCN** [comment]
We will look into updating the doc with a more informative description of the parameter definitions of each integrity error.

Currently the  severity of all INTEGRITY_CHECK errors are `Error` - if we ever introduce any INTEGRITY_CHECK errors with severity `Warning`, then we will update the doc to be more specific.

**Comment by jbraschler** [comment]
In the INTEGRITY_CHECK validation layer, do all rules get evaluated before a response is generated, or will it log one error at a time (or a combination of those)? For example, if you're validating a document that logs the AUTHOR_INSTITUTION_NOT_FOUND error due to a missing or invalid SOR, and there's also a missing SOR on the Responsible Department of an Encounter in the document, will a SOR_IDENTIFIER_EXPECTED error also get logged for the Encounter?

**Comment by TueCN** [comment]
When an INTEGRITY_CHECK error is encountered, all further validation processing stops to prevent hard faults like Java NullPointerException or StackOverflowError and the INTEGRITY_CHECK error is returned.

Please do not rely on there always only being a single INTEGRITY_CHECK error in a response. We may change this behavior in the future.

**Pull request merged**
